# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deployment RESTful API on Python with FastAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    PROJECT_NAME: "Our Mall - OAuth2"
    PROJECT_DESCRIPTION: "Servidor de autorizacion del proyecto Our Mall"
    PROJECT_VERSION: "v0.8.0"
    MONGO_PORT: 27017
    MONGO_HOST: "ourmallcluster.ws6l0.mongodb.net"
    MONGO_USERNAME: "om-agent"
    MONGO_PASSWORD: "1098306124ourMall"
    MONGO_URI: "mongodb+srv://om-agent:1098306124ourMall@ourmallcluster.ws6l0.mongodb.net/?retryWrites=true&w=majority"
    MONGO_DATABASE: "ourMallDB"
    PROJECT_SECRET_KEY: "18f83ec5636e2916dbf27361a19b0bc45a0a9a457ba986b911d09793ea340792"
    SMTP_HOSTNAME: "smtp.gmail.com"
    SMTP_PORT: 587
    SMTP_USERNAME: "our.mall.reply@gmail.com"
    SMTP_PASSWORD: "ogworwprmoaycidf"
    TWILIO_SID: "AC9ccc4138f66a0352e3b9fa93c2a371c0"
    TWILIO_TOKEN: "c1980e00a39a2a42341386ac09cbeb2c"
    TWILIO_PHONE_NUMBER: "+19403405236"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10' # 3.9

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'api-ourmall'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FB339A9A8E754C18A3DBD9794F5838FF }}
